# docker-compose up -d
version: "3.8"
services:
  backend_blue:
    image: gauravj00/todo-backend:latest
    container_name: backend_blue
    networks: [todo-net]
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,backend_blue,backend_blue_upstream,backend_green_upstream
    ports:
      - "8001:8000"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health/').read()"]
      interval: 10s
      timeout: 5s
      retries: 5


  backend_green:
    image: gauravj00/todo-backend:latest
    container_name: backend_green
    networks: [todo-net]
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,backend_green,backend_green_upstream,backend_blue_upstream
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health/').read()"]
      interval: 10s
      timeout: 5s
      retries: 5


  frontend_blue:
    image: gauravj00/todo-frontend:latest
    container_name: frontend_blue
    networks: [todo-net]
    ports:
      - "3001:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend_green:
    image: gauravj00/todo-frontend:latest
    container_name: frontend_green
    networks: [todo-net]
    ports:
      - "3000:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:stable
    container_name: todo_nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks: [todo-net]

networks:
  todo-net:
